apiVersion: v1
kind: Secret
metadata:
  name: secret-devana-production
  namespace: devana-production
type: Opaque
stringData:
  LICENCE: "<LICENCE>"

  # ------------------------------------
  #           Général
  # -------------------------------------
  #
  # --- Application configuration ---
  PORT: "4666"
  APPLICATION_URL: https://app.devana.ai/
  CLIENT_URI: https://app.devana.ai
  API_URI: https://api.devana.ai/
  PDF_TO_WORD_SERVER: devana-docx-service:4667
  JWT_SECRET_KEY: <JWT_SECRET_KEY>

  #
  # --- Internal services configuration ---
  # Database URLs
  DATABASE_URL: postgresql://.../devana?schema=devana
  CHROMA_HOST: http://devana-vectors-service:8000
  # Redis configurations
  REDIS_HOST: devana-redis-service
  REDIS_PORT: "6379"
  REDIS_PASSWORD: default-redis-password
  EMBEDDING: openai # Use database for specific embedding

  # 
  # --- Connectors configuration ---
  # 
  # GOOGLE_CLIENT_ID:
  # GOOGLE_CLIENT_SECRET:
  # DROPBOX_CLIENT_ID: 
  # DROPBOX_CLIENT_SECRET: 
  # MICROSOFT_CLIENT_ID: 
  # MICROSOFT_CLIENT_SECRET: 
  # MICROSOFT_TENANT_ID: common
  # OAUTH_CALLBACK_URI: https://api.devana.ai/api/devana_api_service/oauth2callback
  
  #
  # --- External services configuration ---
  # AI API keys
  # OPENAI_API_KEY: 
  # EMBEDDING: openai
  # DEEPL_KEY: 
  # ANTHROPIC_API_KEY:
  # MISTRAL_API_KEY:
  # GROQ_API_KEY: 
  # GEMINI_API_KEY:

  # Mailjet configuration
  # MAILJET_TEMPLATE_ID:
  # MAILJET_APIKEY_PUBLIC:
  # MAILJET_APIKEY_PRIVATE:

  # 
  # --- AWS Bedrock configuration ---
  #
  # AWS_BEDROCK_ACCESS_KEY_ID: 
  # AWS_BEDROCK_SECRET_ACCESS_KEY:

  #
  # --- AWS S3 configuration ---
  #
  # AWS_S3_ACCESS_KEY_ID: 
  # AWS_S3_SECRET_ACCESS_KEY:
  # AWS_S3_ENPOINT:
  # AWS_S3_REGION:
  # AWS_S3_BUCKET:

  #
  # -- SerpApi ---
  #
  # SEARCH_API_KEY: 

  #
  # --- Proxy Crawbase ---
  #
  # CRAWLBASE_TOKEN:

  #
  # --- Update Metrics Token ---
  # 
  # TOKEN_METRICS: 

  # Google Credentials Path
  # GOOGLE_APPLICATION_CLIENT_EMAIL:
  # GOOGLE_APPLICATION_PRIVATE_KEY:

  # ------------------------------------
  #           Devana Frontend
  # -------------------------------------
  # NextAuth Configuration
  # NEXTAUTH_URL: https://app.devana.ai/
  # NEXTAUTH_SECRET:

  # App configuration
  # ENABLE_OPENREPLAY: "false"
  # 
  # --- Github Oauth Apps Keys ---
  # GITHUB_ID:
  # GITHUB_SECRET:

  # --- Google Keys ---
  # GOOGLE_ID: 
  # GOOGLE_SECRET: 
  # GOOGLE_TRANSLATE_API_KEY: 

  # --- Facebook Keys ---
  # FACEBOOK_ID: 
  # FACEBOOK_SECRET: 

  # Kubernetes (K8s) configuration for WM
  # KUBE_CONFIG:
  # KUBE_NAMESPACE: