apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-devana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devana-redis
  template:
    metadata:
      labels:
        app: devana-redis
    spec:
      containers:
        - name: redis
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
            requests:
              cpu: "0.1"
              memory: "256Mi"
          image: redis
          ports:
            - containerPort: 6379
          command: ["redis-server"]
          args:
            - "--requirepass"
            - "$(REDIS_PASSWORD)"
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-devana
                  key: REDIS_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: devana-redis-service
spec:
  selector:
    app: devana-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
