apiVersion: apps/v1
kind: Deployment
metadata:
  name: devana-api
  namespace: devana-production
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: devana-api
  template:
    metadata:
      labels:
        app: devana-api
    spec:
      containers:
        - name: devana-api
          resources:
            requests:
              cpu: "0.1"
              memory: "400Mi"
            limits:
              cpu: "8"
              memory: "2.5Gi"
          image: registry.devana.ai/devana/back:latest
          ports:
            - containerPort: 4666
            - containerPort: 5001
          livenessProbe:
            httpGet:
              path: /health
              port: 4666
            initialDelaySeconds: 15
            periodSeconds: 15
            timeoutSeconds: 3
            failureThreshold: 3
          env:
            - name: LICENCE
              valueFrom:
                secretKeyRef:
                  name: secret-devana-production
                  key: LICENCE
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: secret-devana-production
                  key: PORT
            - name: EMBEDDING
              valueFrom:
                secretKeyRef:
                  name: secret-devana-production
                  key: EMBEDDING
            - name: APPLICATION_URL
              valueFrom:
                secretKeyRef:
                  name: secret-devana-production
                  key: APPLICATION_URL
            - name: API_URI
              valueFrom:
                secretKeyRef:
                  name: secret-devana-production
                  key: API_URI
            - name: PDF_TO_WORD_SERVER
              valueFrom:
                secretKeyRef:
                  name: secret-devana-production
                  key: PDF_TO_WORD_SERVER
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: secret-devana-production
                  key: JWT_SECRET_KEY
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: secret-devana-production
                  key: DATABASE_URL
            - name: CHROMA_HOST
              valueFrom:
                secretKeyRef:
                  name: secret-devana-production
                  key: CHROMA_HOST
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: secret-devana-production
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: secret-devana-production
                  key: REDIS_PORT
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-devana-production
                  key: REDIS_PASSWORD
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: secret-devana-production
                  key: OPENAI_API_KEY
            - name: DEEPL_KEY
              valueFrom:
                secretKeyRef:
                  name: secret-devana-production
                  key: DEEPL_KEY
            - name: ANTHROPIC_API_KEY
              valueFrom:
                secretKeyRef:
                  name: secret-devana-production
                  key: ANTHROPIC_API_KEY
            - name: MISTRAL_API_KEY
              valueFrom:
                secretKeyRef:
                  name: secret-devana-production
                  key: MISTRAL_API_KEY
            - name: GROQ_API_KEY
              valueFrom:
                secretKeyRef:
                  name: secret-devana-production
                  key: GROQ_API_KEY
            - name: GEMINI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: secret-devana-production
                  key: GEMINI_API_KEY
            - name: MAILJET_TEMPLATE_ID
              valueFrom:
                secretKeyRef:
                  name: secret-devana-production
                  key: MAILJET_TEMPLATE_ID
            - name: MAILJET_APIKEY_PUBLIC
              valueFrom:
                secretKeyRef:
                  name: secret-devana-production
                  key: MAILJET_APIKEY_PUBLIC
            - name: MAILJET_APIKEY_PRIVATE
              valueFrom:
                secretKeyRef:
                  name: secret-devana-production
                  key: MAILJET_APIKEY_PRIVATE
            - name: AWS_BEDROCK_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: secret-devana-production
                  key: AWS_BEDROCK_ACCESS_KEY_ID
            - name: AWS_BEDROCK_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: secret-devana-production
                  key: AWS_BEDROCK_SECRET_ACCESS_KEY
            - name: AWS_S3_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: secret-devana-production
                  key: AWS_S3_ACCESS_KEY_ID
            - name: AWS_S3_ENPOINT
              valueFrom:
                secretKeyRef:
                  name: secret-devana-production
                  key: AWS_S3_ENPOINT
            - name: AWS_S3_REGION
              valueFrom:
                secretKeyRef:
                  name: secret-devana-production
                  key: AWS_S3_REGION
            - name: AWS_S3_ENPOINT
              valueFrom:
                secretKeyRef:
                  name: secret-devana-production
                  key: AWS_S3_ENPOINT
            - name: AWS_S3_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: secret-devana-production
                  key: AWS_S3_SECRET_ACCESS_KEY
            - name: SEARCH_API_KEY
              valueFrom:
                secretKeyRef:
                  name: secret-devana-production
                  key: SEARCH_API_KEY
            - name: CRAWLBASE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: secret-devana-production
                  key: CRAWLBASE_TOKEN
            - name: TOKEN_METRICS
              valueFrom:
                secretKeyRef:
                  name: secret-devana-production
                  key: TOKEN_METRICS
            - name: GOOGLE_APPLICATION_CLIENT_EMAIL
              valueFrom:
                secretKeyRef:
                  name: secret-devana-production
                  key: GOOGLE_APPLICATION_CLIENT_EMAIL
            - name: GOOGLE_APPLICATION_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: secret-devana-production
                  key: GOOGLE_APPLICATION_PRIVATE_KEY
            - name: CLIENT_URI
              valueFrom:
                secretKeyRef:
                  name: secret-devana-production
                  key: CLIENT_URI
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: secret-devana-production
                  key: GOOGLE_CLIENT_ID
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: secret-devana-production
                  key: GOOGLE_CLIENT_SECRET
            - name: DROPBOX_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: secret-devana-production
                  key: DROPBOX_CLIENT_ID
            - name: DROPBOX_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: secret-devana-production
                  key: DROPBOX_CLIENT_SECRET
            - name: MICROSOFT_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: secret-devana-production
                  key: MICROSOFT_CLIENT_ID
            - name: MICROSOFT_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: secret-devana-production
                  key: MICROSOFT_CLIENT_SECRET
            - name: OAUTH_CALLBACK_URI
              valueFrom:
                secretKeyRef:
                  name: secret-devana-production
                  key: OAUTH_CALLBACK_URI
            - name: MICROSOFT_TENANT_ID
              valueFrom:
                secretKeyRef:
                  name: secret-devana-production
                  key: MICROSOFT_TENANT_ID
      imagePullSecrets:
        - name: devana-registry
---
apiVersion: v1
kind: Service
metadata:
  name: devana-api-service
  namespace: devana-production
spec:
  selector:
    app: devana-api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 4666
    - name: ws
      protocol: TCP
      port: 5001
      targetPort: 5001
# ---
# apiVersion: autoscaling/v2
# kind: HorizontalPodAutoscaler
# metadata:
#   name: devana-api-hpa
#   namespace: devana-production
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: devana-api
#   minReplicas: 3
#   maxReplicas: 3
#   metrics:
#   - type: Resource
#     resource:
#       name: cpu
#       target:
#         type: Utilization
#         averageUtilization: 70
#   - type: Resource
#     resource:
#       name: memory
#       target:
#         type: Utilization
#         averageUtilization: 75
#   behavior:
#     scaleDown:
#       stabilizationWindowSeconds: 300
#       policies:
#       - type: Pods
#         value: 1
#         periodSeconds: 60
#     scaleUp:
#       stabilizationWindowSeconds: 60
#       policies:
#       - type: Pods
#         value: 2
#         periodSeconds: 30