apiVersion: apps/v1
kind: Deployment
metadata:
  name: devana-docx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devana-docx
  template:
    metadata:
      labels:
        app: devana-docx
    spec:
      containers:
        - name: devana-docx
          resources:
            limits:
              cpu: "2"
              memory: "1Gi"
            requests:
              cpu: "100m"
              memory: "256Mi"
          image: registry.devana.ai/devana/pdfdocx:latest
          ports:
            - containerPort: 4667
          env:
            - name: NODE_ENV
              value: "production"
      imagePullSecrets:
        - name: devana-registry
---
apiVersion: v1
kind: Service
metadata:
  name: devana-docx-service
spec:
  selector:
    app: devana-docx
  ports:
    - protocol: TCP
      port: 4667
      targetPort: 4667
