apiVersion: apps/v1
kind: Deployment
metadata:
  name: devana-vectors
  namespace: devana-production
  labels:
    app: devana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devana-vectors
  template:
    metadata:
      labels:
        app: devana-vectors
        tier: devana-vectors
    spec:
      containers:
        - name: devana-vectors
          image: registry.devana.ai/devana/devana-vectors:0.4.18
          resources:
            limits:
              cpu: "4"
              memory: "3Gi"
            requests:
              cpu: "100m"
              memory: "256Mi"
          ports:
            - containerPort: 8000
          env:
          - name: IS_PERSISTENT
            value: "true"
          volumeMounts:
          - name: vectors-volume-production-mount
            mountPath: /chroma/.chroma/index
      imagePullSecrets:
        - name: devana-registry
      volumes:
        - name: vectors-volume-production-mount
          persistentVolumeClaim:
            claimName: vectors-pvc-production
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vectors-pvc-production
  namespace: devana-production
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
--- 
apiVersion: v1
kind: Service
metadata:
  name: devana-vectors-service
  namespace: devana-production
spec:
  selector:
    app: devana-vectors
    tier: devana-vectors
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000


