apiVersion: apps/v1
kind: Deployment
metadata:
  name: devana-meilisearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devana-meilisearch
  template:
    metadata:
      labels:
        app: devana-meilisearch
    spec:
      containers:
        - name: devana-meilisearch
          resources:
            limits:
              cpu: "4"
              memory: "3Gi"
            requests:
              cpu: "100m"
              memory: "256Mi"
          image: getmeili/meilisearch:v1.9
          ports:
            - containerPort: 7700
          env:
            - name: MEILI_MASTER_KEY
              value: "EXAMPLE_MASTER_KEY"
          volumeMounts:
            - name: meilisearch-volume
              mountPath: /meili_data
      volumes:
        - name: meilisearch-volume
          persistentVolumeClaim:
            claimName: meilisearch
      imagePullSecrets:
        - name: registry-secret-scriptor
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: meilisearch
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  volumeMode: Filesystem
---
apiVersion: v1
kind: Service
metadata:
  name: devana-meilisearch-service
spec:
  selector:
    app: devana-meilisearch
  ports:
    - protocol: TCP
      port: 7700
      targetPort: 7700
