apiVersion: apps/v1
kind: Deployment
metadata:
  name: devana-api
  namespace: devana
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: devana-api
  template:
    metadata:
      labels:
        app: devana-api
    spec:
      containers:
        - name: devana-api
          resources:
            requests:
              cpu: "3"
              memory: "4Gi"
            limits:
              cpu: "3"
              memory: "4Gi"
          image: registry.devana.ai/devana/back:latest
          ports:
            - containerPort: 4666
            - containerPort: 5001
          livenessProbe:
            httpGet:
              path: /health
              port: 4666
            initialDelaySeconds: 15
            periodSeconds: 15
            timeoutSeconds: 3
            failureThreshold: 3
          env:
            - name: CHECKPOINT_DISABLE # Disable prisma telemetry
              value: "1"
            # --- Application Configuration ---
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: secret-devana
                  key: JWT_SECRET_KEY
            - name: LICENCE
              valueFrom:
                secretKeyRef:
                  name: secret-devana
                  key: LICENCE
            - name: CLIENT_URI
              valueFrom:
                secretKeyRef:
                  name: secret-devana
                  key: CLIENT_URI
            - name: API_URI
              valueFrom:
                secretKeyRef:
                  name: secret-devana
                  key: API_URI
            # --- Services Configuration ---
            - name: ODIN_API_URL
              valueFrom:
                secretKeyRef:
                  name: secret-devana
                  key: ODIN_API_URL
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: secret-devana
                  key: DATABASE_URL
            - name: CHROMA_HOST
              valueFrom:
                secretKeyRef:
                  name: secret-devana
                  key: CHROMA_HOST
            - name: CHROMA_API_KEY
              valueFrom:
                secretKeyRef:
                  name: secret-devana
                  key: CHROMA_API_KEY
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: secret-devana
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: secret-devana
                  key: REDIS_PORT
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-devana
                  key: REDIS_PASSWORD
            - name: AWS_S3_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: secret-devana
                  key: S3_ENDPOINT
            - name: AWS_S3_REGION
              valueFrom:
                secretKeyRef:
                  name: secret-devana
                  key: S3_REGION
            - name: S3_PUBLIC_URL
              valueFrom:
                secretKeyRef:
                  name: secret-devana
                  key: S3_PUBLIC_URL
            - name: CLOUD_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: secret-devana
                  key: S3_BUCKET
            - name: AWS_S3_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: secret-devana
                  key: AWS_S3_ACCESS_KEY_ID
            - name: AWS_S3_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: secret-devana
                  key: AWS_S3_SECRET_ACCESS_KEY
            - name: MEILI_HOST
              valueFrom:
                secretKeyRef:
                  name: secret-devana
                  key: MEILI_HOST
            - name: MEILI_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: secret-devana
                  key: MEILI_MASTER_KEY
            - name: EMBEDDING_JSON
              valueFrom:
                secretKeyRef:
                  name: secret-devana
                  key: EMBEDDING_JSON
      imagePullSecrets:
        - name: devana-registry
---
apiVersion: v1
kind: Service
metadata:
  name: devana-api-service
  namespace: devana
spec:
  selector:
    app: devana-api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 4666
    - name: ws
      protocol: TCP
      port: 5001
      targetPort: 5001