apiVersion: v1
kind: Secret
metadata:
  name: secret-devana
  namespace: devana
type: Opaque
stringData:
  #
  # --- Application Configuration ---
  #
  JWT_SECRET_KEY: "ChangeMe"
  ## Devana API
  LICENCE: ""
  CLIENT_URI: https://example.com
  API_URI: https://api.example.com/
  ## Devana Frontend
  ### Authentification
  NEXTAUTH_URL: https://example.com/
  NEXTAUTH_SECRET: "ChangeMe2"
  ## Odin
  DEVANA_API_URL: http://devana-api-service

  #
  # --- Services Configuration ---
  #
  # ODIN
  ODIN_API_URL: http://devana-odin-service:3003
  ## PostgreSQL
  DATABASE_URL: postgresql://user:ChangeMe5@postgresql:5432/devana?schema=devana
  DATABASE_URL_ODIN: postgresql://user:ChangeMe5@postgresql:5432/devana?schema=odin
  ## Chroma
  CHROMA_HOST: http://devana-chroma-service:8000
  CHROMA_API_KEY: "CHANGEME6"
  ## Redis
  REDIS_HOST: devana-redis-service
  REDIS_PORT: "6379"
  REDIS_PASSWORD: "ChangeMe3"
  ## S3
  S3_ENDPOINT: ""
  S3_REGION: ""
  S3_PUBLIC_URL: ""
  S3_BUCKET: ""
  AWS_S3_ACCESS_KEY_ID: ""
  AWS_S3_SECRET_ACCESS_KEY: ""
  ## MeiliSearch
  MEILI_HOST: http://devana-meilisearch-service:7700
  MEILI_MASTER_KEY: "ChangeMe4"
  EMBEDDING_JSON: '{"model": "model","apiKey":"apikey","configuration":{"baseURL":"http://example.com/v1"}}'
  VISION_JSON: '{"model": "model","apiKey":"apikey","configuration":{"baseURL":"http://example.com/v1"}}'