apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-devana
  namespace: devana-production
  labels:
    app: devana-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devana-redis
      tier: redis
  template:
    metadata:
      labels:
        app: devana-redis
        tier: redis
    spec:
      containers:
        - name: redis
          image: redis
          command: ["redis-server"]
          args: ["--requirepass", "default-redis-password"]  # Use a secret for REDIS_PASSWORD
          ports:
            - containerPort: 6379
              name: redis
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
            requests:
              cpu: "0.1"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: devana-redis-service
  namespace: devana-production
spec:
  selector:
    app: devana-redis
    tier: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
