name: Restart doc.devana.ai

concurrency:
    group: deploy-production
    cancel-in-progress: true

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    restart:
        runs-on: ubuntu-latest

        steps:
            - name: Update Documentation image
              uses: actions-hub/kubectl@master
              env:
                  KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
              with:
                  args: rollout restart deployment/devana-docs --namespace=devana-production
